server:
  port: 8080

spring:
  datasource:
    url: incurance-policy.cfwpjgkmdv6h.us-east-1.rds.amazonaws.com
    username: admin
    password: 123admin
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
